# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:

# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.

# Serve data.
- url: /data
  static_dir: data
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: /images
  static_dir: images
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js

- url: /
  static_files: 'index.html'
  upload: 'index.html'

- url: .*  # This regex directs all routes to main.app
  script: main.app
